# Generated by Django 4.2.1 on 2023-07-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdmcApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=13)),
            ],
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='componentName',
            field=models.CharField(choices=[('hw', 'height/ weight'), ('bp', 'Blood Pressure'), ('hrt', 'Heart rate')], max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sdmcApp.doctor'),
        ),
    ]
